name: Bug report
description: Report errors or unexpected behavior.
labels: [bug]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting issues of HMAL!

        To prevent spam, please fill in the title after "[Bug]".

        To make it easier for us to help you please enter detailed information below.
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      placeholder: Tell us what should happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
      placeholder: Tell us what happens instead
    validations:
      required: true
  - type: textarea
    attributes:
      label: Xposed Module List
      render: Shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Magisk Module List
      render: Shell
    validations:
      required: true
  - type: input
    attributes:
      label: HMAL version/HMAL
      description:  Please check [Actions](https://github.com/pumPCin/HMAL/actions/workflows/main.yml) for the latest CI debug build. Don't just type "latest". Specify actual version (**MUST** contains `.rXXX.XXX-debug`), otherwise your issue will be closed.
      placeholder: V_._._(-Beta).r___._______-debug
    validations:
      required: true
  - type: input
    attributes:
      label: Android version
    validations:
      required: true
  - type: input
    attributes:
      label: Magisk version
    validations:
      required: true
  - type: dropdown
    id: latest
    attributes:
      label: Version requirement
      description: Select the version being used for feedback.
      multiple: false
      options:
        - Latest CI debug build
        - Version required by the developer
        - Public release/beta version
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: For usage issues, please provide the log zip saved from manager; for activation issues, please provide [bugreport](https://developer.android.com/studio/debug/bug-report). Without log, the issue will be closed.
      placeholder: Upload logs by clicking the bar on the bottom.
    validations:
      required: true
